name: Bump version

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: false
        default: 'v'
        type: string
    outputs:
      tag:
        description: Newly created tag
        value: ${{ jobs.bump-version.outputs.tag }}

jobs:
  bump-version:
    name: Bump Version on master
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      tag: ${{ steps.save-tag.outputs.tag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: ${{ inputs.tag-prefix }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: cat package.json
        run: cat ./package.json

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

      - name: Save tag to workflow output
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        id: save-tag
        run: echo "tag=$NEW_TAG" >> "$GITHUB_OUTPUT"
